### ISSUE TITLE
Incorrect Youtube link and other suggestions

### ISSUE THREAD

**Issue by aquaductape** [sjdonado/idonthavespotify#1]
This for the Web page, not Raycast Extension.

When pasting "S5E5 Framework Building with Ryan Carniato" link https://open.spotify.com/episode/5dNTXSZtkQLm6HuVdboFtx?si=40b29ad1f62742b5, The youtube link is incorrect, leads to ryan's "JavaScript Frameworks in 2023" https://www.youtube.com/watch?v=6RIPfwxj24s

Also I'd suggest not showing other platform links if they don't exist.

**Comment by sjdonado** [comment]
@aquaductape Noted. Thanks for opening the issue, it's a good idea not to show links if it's Spotify exclusive content. on it
