### ISSUE TITLE
Support localized Spotify links

### ISSUE THREAD

**Issue by fgsalomon** [sjdonado/idonthavespotify#29]
Hi,

Great project!

I've just tested it with a link generated by my Spotify client and it didn't work because it seems that the link is Spanish localized:
`https://open.spotify.com/intl-es/track/5OPT7l9b5SMwfTQgLPoNl7?si=c99be1762ac64e2d`
I could make it work by removing the substring `intl-es/`, but I think it would be nice if the URL got automatically sanitized.

**Comment by sjdonado** [comment]
closed by https://github.com/sjdonado/idonthavespotify/pull/30
