### ISSUE TITLE
Inverse search?

### ISSUE THREAD

**Issue by fbracht** [sjdonado/idonthavespotify#6]
Hi!

For the same reasons why I would like to convert a Spotify link into a non-Spotify one, I also frequently find myself wanting to convert a non-Spotify link into a Spotify one. Would it be possible to implement the inverse functionality? (As in, pasting an Apple Music link and getting in return a Spotify link to the same item.)

Thanks!

**Comment by sjdonado** [comment]
@fbracht good idea!

I can work on it, starting next month :)
